### ISSUE TITLE
Platformer2D builds on Windows 10 but not on macOS 10.15.1

### ISSUE THREAD

**Issue by willowell** [MonoGame/MonoGame.Samples#48]
Solution tried on Windows 10: Samples-WindowsDX.sln
Solution tried on macOS 10.15.1: Samples-OSX.sln

Mono version: 6.4.0.208 (2019-06/07c23f2ca43 Wed Oct  2 04:52:23 EDT 2019)
MonoGame version: 3.7.1
Visual Studio for Mac version: 8.3.10

Upon opening Samples-OSX.sln, Visual Studio reported that it could not find Lidgren.Network.MacOS.csproj or MonoGame.Framework.MacOS.csproj. The Platformer2D project has a warning on it that the MonoMac extension is not installed.

I then removed Lidgren.Network.MacOS and MonoGame.Framework.MacOS from the solution.

I then downloaded the MonoGame 3.7.1 source code, put it in my home directory (/Users/$name), built it with "mono Protobuild.exe," and then copied Lidgren.Network.MacOS.csproj and MonoGame.Framework.Net.MacOS.csproj into the solution.

Building it results in two warnings and one error:
• The two included projects cannot find the assemly System.Drawing.Common.dll
• /Users/$name/MonoGame-3.7.1/MonoGame.Framework/CSC: Error CS0006: Metadata file '/Users/$name/MonoGame-3.7.1/MonoGame.Framework/bin/MacOS/AnyCPU/Debug/MonoGame.Framework.dll' could not be found (CS0006) (MonoGame.Framework.Net.MacOS)

Additionally, the Platformer2D.csproj file defines `DEBUG MONOMAC` but not `MONOMAC` on its own, so I do not know if `Program.cs(2): #if MONOMAC` even works.

I also do not know if the `using` statements at the top of `Program.cs` are still valid now that Xamarin.Mac is a thing. I know that Microsoft's Xamarin "Hello_Mac" sample works just fine for me, so `using AppKit; using Foundation;` should be fine, but it seems that I would have to add Xamarin.Mac to the solution for that. I have not yet tried doing that.

Furthermore, the `dotnet mgdesktopgl` template builds just fine for me, so I am assuming that MonoMac/Xamarin.Mac is why Platformer2D refuses to build for me.

**Comment by SimonDarksideJ** [comment]
Will validate this as part of the 3.8 upgrade #50
